name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: npm install -g npm@latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C ts test
      - run: pnpm -C ts build
      - run: npm publish --access public
        working-directory: ts
